name: insugent
description: A Companion App for Insurance Agents

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.0
  shared_preferences: ^2.0.5
  http: ^0.13.1
  uuid: ^3.0.4
  intl: ^0.17.0
  adaptive_breakpoints: ^0.0.4
  url_launcher: ^6.0.3
  google_sign_in: ^5.0.1
  cloud_firestore: ^1.0.4
  firebase_core: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "res/insugent.png"

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - res/insugent.png
    - res/google.png
    - res/brands.json

  fonts:
    - family:  outline_material_icons
      fonts:
        - asset: res/outline_material_icons.ttf